name: push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
    - name: Publish Nuget Panosen.CodeDom.Tag
      run: dotnet nuget push Panosen.CodeDom.Tag/bin/Release/Panosen.CodeDom.Tag.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.CodeDom.Tag.Core
      run: dotnet nuget push Panosen.CodeDom.Tag.Core/bin/Release/Panosen.CodeDom.Tag.Core.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.CodeDom.Tag.Engine
      run: dotnet nuget push Panosen.CodeDom.Tag.Engine/bin/Release/Panosen.CodeDom.Tag.Engine.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.CodeDom.Tag.Html
      run: dotnet nuget push Panosen.CodeDom.Tag.Html/bin/Release/Panosen.CodeDom.Tag.Html.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
    - name: Publish Nuget Panosen.CodeDom.Tag.Html.Engine
      run: dotnet nuget push Panosen.CodeDom.Tag.Html.Engine/bin/Release/Panosen.CodeDom.Tag.Html.Engine.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.PANOSEN_NUGET_API_KEY}} --skip-duplicate
